# Generated by Django 5.2 on 2025-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='حساب کاری فعال است ؟')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='آیا مدیر سایت است')),
                ('is_staff', models.BooleanField(default=False, verbose_name='آیا عضو مدیریت سایت است ؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد حساب')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'user',
                'ordering': ('-created_at',),
            },
        ),
    ]
