# Generated by Django 5.2 on 2025-06-21 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('card_number', models.CharField(max_length=16, verbose_name='کارت بانکی')),
                ('image', models.ImageField(upload_to='partners/profile', verbose_name='تصویر پروفایل')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد همکاری')),
                ('rank', models.CharField(choices=[('bronze', 'برنزی'), ('silver', 'نقره ای'), ('gold', 'طلایی')], default='bronze', max_length=50, verbose_name='سطح کاربر')),
                ('sells', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت همکار')),
                ('is_active', models.BooleanField(default=False, verbose_name='همکار شود ؟')),
                ('commission_can_clime', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=' پورسانت قابل برداشت')),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مجموع پورسانت')),
                ('notification', models.TextField(blank=True, null=True, verbose_name='پیام به همکاران ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'همکار',
                'verbose_name_plural': 'همکاران',
                'db_table': 'partnership',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PartnerMonthlySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('month', models.IntegerField(verbose_name='ماه')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش ماهانه')),
                ('commission_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=' پورسانت ماهانه')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stat', to='account.partnership', verbose_name='همکار')),
            ],
            options={
                'verbose_name': 'عملکرد ماهانه همکار',
                'verbose_name_plural': 'عملکرد های ماهانه همکاران',
                'db_table': 'partner_monthly_set',
                'ordering': ('-year', '-month'),
                'unique_together': {('partner', 'year', 'month')},
            },
        ),
    ]
