# Generated by Django 5.2 on 2025-06-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_partnership_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='notification',
        ),
    ]
