# Generated by Django 5.2 on 2025-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_partnership_eval_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermonthlyset',
            name='monthly_sells',
            field=models.IntegerField(default=0, verbose_name='فروش ماهانه'),
        ),
    ]
