# Generated by Django 5.2 on 2025-06-25 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_partnermonthlyset_monthly_sells'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermonthlyset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
