# Generated by Django 5.2 on 2025-06-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_partnermonthlyset_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermonthlyset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('gift_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد هدیه')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='آیا فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='account.partnership', verbose_name='همکار')),
            ],
            options={
                'verbose_name': 'کد تخفیف کاربر',
                'verbose_name_plural': 'کد های تخفیف کاربران',
                'db_table': 'gift',
                'ordering': ('created_at',),
                'unique_together': {('partner', 'gift_code')},
            },
        ),
    ]
