# Generated by Django 5.2 on 2025-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_partnermonthlyset_created_at_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='کد هدیه'),
        ),
    ]
