# Generated by Django 5.2 on 2025-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_gift_gift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='expire_after_days',
            field=models.PositiveIntegerField(default=0, verbose_name='انقضا پس از چند روز'),
        ),
        migrations.AddField(
            model_name='gift',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر دفعات استفاده'),
        ),
        migrations.AddField(
            model_name='gift',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده'),
        ),
    ]
