# Generated by Django 5.2 on 2025-06-29 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_gift_expire_after_days_gift_max_uses_gift_used_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('card', models.CharField(max_length=22, verbose_name='شماره کارت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_paid', models.BooleanField(default=False, verbose_name='آیا پرداخت شده')),
                ('p_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست برداشت کاربران',
                'db_table': 'withdraw',
                'ordering': ('-created_at',),
            },
        ),
    ]
