# Generated by Django 5.2 on 2025-07-03 11:56

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='partner/prof/'),
        ),
    ]
