# Generated by Django 5.2 on 2025-07-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_partnership_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnership',
            options={'ordering': ('-created_at',), 'verbose_name': 'همکار', 'verbose_name_plural': 'همکاران'},
        ),
    ]
