# Generated by Django 5.2 on 2025-07-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], max_length=10)),
                ('jalali_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='ماه')),
                ('week', models.IntegerField(blank=True, null=True, verbose_name='هفته')),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='روز')),
                ('total_sales', models.PositiveBigIntegerField(default=0, verbose_name='تعداد فروش')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='مقدار فروش')),
            ],
            options={
                'verbose_name': 'آمار فروش سایت',
                'verbose_name_plural': 'آمار فروش های سایت',
                'unique_together': {('type', 'year', 'month', 'week', 'day')},
            },
        ),
    ]
