# Generated by Django 5.2 on 2025-07-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ میلادی'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_sales',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدار فروش'),
        ),
    ]
