# Generated by Django 5.2 on 2025-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_stats_date_alter_stats_total_orders_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('type', 'year', 'month', 'day')},
        ),
        migrations.AlterField(
            model_name='stats',
            name='type',
            field=models.CharField(choices=[('daily', 'روزانه'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='stats',
            name='week',
        ),
    ]
