# Generated by Django 5.2 on 2025-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_stats_unique_together_alter_stats_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='partner_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد خرید همکاران'),
        ),
        migrations.AddField(
            model_name='stats',
            name='partner_sales',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدار خرید همکاران'),
        ),
        migrations.AddField(
            model_name='stats',
            name='partner_signups',
            field=models.PositiveIntegerField(default=0, verbose_name='ثبت\u200cنام همکاران'),
        ),
        migrations.AddField(
            model_name='stats',
            name='user_signups',
            field=models.PositiveIntegerField(default=0, verbose_name='ثبت\u200cنام کاربران'),
        ),
    ]
