# Generated by Django 5.2 on 2025-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_notification_stats_partner_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
