# Generated by Django 5.2 on 2025-06-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('short_desc', models.CharField(max_length=200, verbose_name='توضیح کوتاه')),
                ('desc', models.TextField(verbose_name='توضیح کامل')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='تصویر')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-pub_date'],
            },
        ),
    ]
