# Generated by Django 5.2 on 2025-06-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='desc',
        ),
        migrations.CreateModel(
            name='ArticlePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بخش')),
                ('desc', models.TextField(verbose_name='متن بخش')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='عکس بخش')),
                ('part', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_parts', to='article.article', verbose_name='مقاله اصلی')),
            ],
            options={
                'verbose_name': 'تکه های مقاله',
                'verbose_name_plural': 'تکه های مقالات',
                'db_table': 'article_parts',
                'ordering': ['-part'],
            },
        ),
    ]
