# Generated by Django 5.2 on 2025-06-02 07:24

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_desc_articlepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='دسته بندی ')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی مقالات',
                'db_table': 'article_category',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید ها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='articlepart',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='articles/parts/'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.articlecategory', verbose_name='دسته بندی مقاله '),
        ),
    ]
