# Generated by Django 5.2 on 2025-06-08 13:21

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlecategory_article_slug_article_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
