# Generated by Django 5.2 on 2025-07-03 11:56

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='big_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='article/big/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='article/base/'),
        ),
        migrations.AlterField(
            model_name='articlepart',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='article/detail/'),
        ),
    ]
