# Generated by Django 5.2 on 2025-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_big_image_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='اسلاگ'),
        ),
    ]
