# Generated by Django 5.2 on 2025-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
