# Generated by Django 5.2 on 2025-05-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banners_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='banners',
            new_name='Banner',
        ),
    ]
