# Generated by Django 5.2 on 2025-07-03 11:56

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_banner_banner_image_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='banners/home/'),
        ),
    ]
