# Generated by Django 5.2 on 2025-07-09 17:07

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='banners/home/mobile/', verbose_name='بنر برای موبایل'),
        ),
    ]
