# Generated by Django 5.2 on 2025-07-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_banner_mobile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='mobile_image',
        ),
    ]
