# Generated by Django 5.2 on 2025-05-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link', models.TextField(blank=True, max_length=100, null=True, verbose_name='آدرس صفحه')),
                ('sub_links', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_link', to='site_settings.footer', verbose_name='زیر دسته ها')),
            ],
            options={
                'verbose_name': 'پاورقی',
                'verbose_name_plural': 'پاورقی ها',
                'ordering': ['title'],
            },
        ),
    ]
