# Generated by Django 5.2 on 2025-06-04 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.useraddress', verbose_name='آدرس ارسال'),
        ),
    ]
