# Generated by Django 5.2 on 2025-06-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره فاکتور'),
        ),
    ]
