# Generated by Django 5.2 on 2025-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pishteaz', 'پست پیشتاز'), ('tipax', 'ارسال با تیپاکس')], default='pishteaz', max_length=20, verbose_name='روش ارسال'),
        ),
    ]
