# Generated by Django 5.2 on 2025-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_authority_order_ref_id_alter_order_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='TrackingCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='به دست کاربر رسید'),
        ),
        migrations.AddField(
            model_name='order',
            name='get_in_post',
            field=models.BooleanField(default=False, verbose_name='به پست تحویل داده شد'),
        ),
    ]
