# Generated by Django 5.2 on 2025-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_trackingcode_order_finished_order_get_in_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
