# Generated by Django 5.2 on 2025-05-16 13:59

import django.db.models.deletion
import imagekit.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='نام رنگ')),
                ('hex_color', models.CharField(max_length=7, verbose_name='شناسه رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
                'db_table': 'colors',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='سایز')),
                ('age_min', models.CharField(blank=True, max_length=50, null=True, verbose_name='حداقل سن')),
                ('age_max', models.CharField(blank=True, max_length=50, null=True, verbose_name='حداکثر سن')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
                'db_table': 'color',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/categories/category', verbose_name='عکس دسته بندی')),
                ('sub_category', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category', verbose_name='دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'db_table': 'category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل محصول')),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصد تخفیف')),
                ('has_discount', models.BooleanField(default=False, verbose_name='آیا محصول تخفیف دارد؟')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('age', models.CharField(blank=True, max_length=70, null=True, verbose_name='مناسب چه بازه سنی')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('material', models.CharField(choices=[('cotton', 'پنبه\u200cای'), ('linen', 'کتان'), ('polyester', 'پلی\u200cاستر'), ('wool', 'پشمی'), ('silk', 'ابریشم')], max_length=100, verbose_name='جنس محصول')),
                ('gender', models.CharField(choices=[('boys', 'پسرانه'), ('girls', 'دخترانه'), ('unisex', 'هر دو')], max_length=100, verbose_name='جنسیت')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'db_table': 'product',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='ip کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_visited', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید محصول',
                'verbose_name_plural': 'بازدید های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصد تخفیف')),
                ('has_discount', models.BooleanField(default=False, verbose_name='آیا محصول تخفیف دارد؟')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='تصویر')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'دسته کردن محصول',
                'verbose_name_plural': 'دسته کردن محصولات',
                'db_table': 'product_variant',
                'ordering': ['product', 'color'],
                'unique_together': {('product', 'color')},
            },
        ),
    ]
