# Generated by Django 5.2 on 2025-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
