# Generated by Django 5.2 on 2025-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_uuid_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسلاگ'),
        ),
    ]
