# Generated by Django 5.2 on 2025-05-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_views_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='قطعه لباس')),
            ],
            options={
                'verbose_name': 'قطعه لباس',
                'verbose_name_plural': 'قطعات لباس',
            },
        ),
        migrations.CreateModel(
            name='PartAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ویژگی اندازه\u200cگیری')),
            ],
            options={
                'verbose_name': 'ویژگی اندازه\u200cگیری',
                'verbose_name_plural': 'ویژگی\u200cهای اندازه\u200cگیری',
            },
        ),
        migrations.CreateModel(
            name='MeasurementPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.clothespart', verbose_name='قطعه لباس')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'الگوی اندازه\u200cگیری',
                'verbose_name_plural': 'الگوهای اندازه\u200cگیری',
                'unique_together': {('clothing_part', 'size')},
            },
        ),
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.measurementpreset', verbose_name='الگوی اندازه\u200cگیری')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.partattribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار اندازه\u200cگیری',
                'verbose_name_plural': 'مقادیر اندازه\u200cگیری',
            },
        ),
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measurementpreset', verbose_name='الگوی اندازه\u200cگیری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'اتصال محصول به اندازه\u200cها',
                'verbose_name_plural': 'اتصالات محصولات به اندازه\u200cها',
                'unique_together': {('product', 'preset')},
            },
        ),
    ]
