# Generated by Django 5.2 on 2025-06-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_total_stock_productvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا تخفیف'),
        ),
    ]
