# Generated by Django 5.2 on 2025-07-03 11:56

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_discount_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/variant/'),
        ),
    ]
