# Generated by Django 5.2 on 2025-07-05 11:33

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
