# Generated by Django 5.2 on 2025-07-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
