# Generated by Django 5.2 on 2025-06-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_contactus', '0003_alter_replycontact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycontact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده '),
        ),
    ]
