# Generated by Django 5.2 on 2025-06-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_contactus', '0004_replycontact_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycontact',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_contact', to='aboutus_contactus.contactus', verbose_name='پاسخ به پیام'),
        ),
    ]
