# Generated by Django 5.2 on 2025-07-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_contactus', '0005_alter_replycontact_reply_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
